<html>
<head>
    <title>Login</title>
</head>
<body>
<div class="section">
    <div id="message" class="error-text">$message$</div>
    <form method="POST">
        <p>Username</p>
        <p><input name="username" value="$username$" type="text"/></p>
        <p>Password</p>
        <p><input name="password" value="" type="password"/></p>
        <p><input type="submit" value="login" /></p>
    </form>
</div>
</body>
</html>