<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>$title$</title>
</head>
<body>
<div class="section">
    <h2>Revision $revisionNumber$ (read only)</h2>

    <p>The latest revision can be seen at <a href="$latestRevisionUrl$">$latestRevisionUrl$</a></p>

    <div height="100%">
        <textarea readonly="true" style="width:100%;height:300px;max-height:100%;border:1px solid black;overflow:auto;">$properties:htmlproperty()$</textarea>
    </div>
</div>

</body>
</html>